### ISSUE TITLE
installation according to readme instructions does not work

### ISSUE THREAD

**Issue by mvernacc** [upsideon/quantum-subset-sum#1]
I attempted to install `qss` in a new venv via `pip install .` as instructed in the readme. That command succeeded, but subsequently `import qss` throws a `ModuleNotFoundError`.

This error can be resolved by changing line 10 of `setup.py` from
```python
    requires=["numpy", "qiskit",],
```
to
```python
    install_requires=["numpy", "qiskit",],
```
so that the `qiskit` and `numpy` dependencies are properly installed. I think `install_requires` is the keyword argument for [setuptools](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html) setup function, whereas `requires` is a kwarg for the [distutils](https://docs.python.org/3.10/distutils/setupscript.html#relationships-between-distributions-and-packages) setup function.

**Comment by upsideon** [comment]
Thank you for bringing this to my attention and proposing a fix, @mvernacc! I've updated `setup.py` accordingly and have confirmed that the module installation process works in a fresh virtual environment. Changes were applied [in this commit](https://github.com/upsideon/quantum-subset-sum/commit/cc7eba681b44d0580bfb0e4216e8d1b735c13437).
